# .github/workflows/generate_calendar.yml

name: Generate Calendar

on:
  schedule:
    # 每年1月1日凌晨2点（北京时间）运行
    - cron: '0 18 31 12 *'  # UTC时间，对应北京时间次日凌晨2点
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate calendar
      run: python calendar_generator.py
      env:
        IS_FIRST_WEEK_SMALL: ${{ secrets.IS_FIRST_WEEK_SMALL }}
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.ics
        git commit -m "Update calendar for new year" || exit 0
        git push
